CREATE TYPE "public"."account_type" AS ENUM('checking', 'credit', 'cash', 'savings');--> statement-breakpoint
CREATE TYPE "public"."category_kind" AS ENUM('expense', 'income');--> statement-breakpoint
CREATE TYPE "public"."txn_direction" AS ENUM('debit', 'credit');--> statement-breakpoint
CREATE TYPE "public"."txn_source" AS ENUM('manual', 'email', 'receipt', 'bank');--> statement-breakpoint
CREATE TYPE "public"."txn_status" AS ENUM('confirmed', 'pending_review');--> statement-breakpoint
CREATE TABLE "accounts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"type" "account_type" NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "budgets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"category_id" uuid NOT NULL,
	"month" date NOT NULL,
	"amount" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"kind" "category_kind" NOT NULL,
	"color" text DEFAULT '#64748b' NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"currency" text DEFAULT 'USD' NOT NULL,
	"onboarded_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "transactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"account_id" uuid NOT NULL,
	"category_id" uuid,
	"amount" integer NOT NULL,
	"direction" "txn_direction" NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"note" text,
	"source" "txn_source" DEFAULT 'manual' NOT NULL,
	"source_ref" text,
	"status" "txn_status" DEFAULT 'confirmed' NOT NULL,
	"is_transfer" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "budgets" ADD CONSTRAINT "budgets_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "accounts_user_idx" ON "accounts" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "budgets_user_category_month_uq" ON "budgets" USING btree ("user_id","category_id","month");--> statement-breakpoint
CREATE INDEX "budgets_user_month_idx" ON "budgets" USING btree ("user_id","month");--> statement-breakpoint
CREATE INDEX "categories_user_idx" ON "categories" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "transactions_user_occurred_idx" ON "transactions" USING btree ("user_id","occurred_at");--> statement-breakpoint
CREATE INDEX "transactions_category_idx" ON "transactions" USING btree ("category_id");--> statement-breakpoint
CREATE UNIQUE INDEX "transactions_source_ref_uq" ON "transactions" USING btree ("user_id","source","source_ref") WHERE "transactions"."source_ref" is not null;--> statement-breakpoint
-- ===========================================================================
-- Hand-authored (not generated by drizzle-kit): auth.users FKs, CHECK
-- constraints, RLS + policies, the signup seed trigger, realtime publication.
-- See docs/conventions.md -> "Building a feature - the layer order", step 1.
-- ===========================================================================
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_id_auth_users_fk" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "budgets" ADD CONSTRAINT "budgets_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_amount_positive" CHECK ("amount" > 0);--> statement-breakpoint
ALTER TABLE "budgets" ADD CONSTRAINT "budgets_amount_nonnegative" CHECK ("amount" >= 0);--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "accounts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "transactions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "budgets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "own profile" ON "profiles" FOR ALL TO authenticated USING ((SELECT auth.uid()) = "id") WITH CHECK ((SELECT auth.uid()) = "id");--> statement-breakpoint
CREATE POLICY "own accounts" ON "accounts" FOR ALL TO authenticated USING ((SELECT auth.uid()) = "user_id") WITH CHECK ((SELECT auth.uid()) = "user_id");--> statement-breakpoint
CREATE POLICY "own categories" ON "categories" FOR ALL TO authenticated USING ((SELECT auth.uid()) = "user_id") WITH CHECK ((SELECT auth.uid()) = "user_id");--> statement-breakpoint
CREATE POLICY "own transactions" ON "transactions" FOR ALL TO authenticated USING ((SELECT auth.uid()) = "user_id") WITH CHECK ((SELECT auth.uid()) = "user_id");--> statement-breakpoint
CREATE POLICY "own budgets" ON "budgets" FOR ALL TO authenticated USING ((SELECT auth.uid()) = "user_id") WITH CHECK ((SELECT auth.uid()) = "user_id");--> statement-breakpoint
CREATE OR REPLACE FUNCTION "public"."handle_new_user"()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id) VALUES (NEW.id);

  INSERT INTO public.accounts (user_id, name, type)
  VALUES (NEW.id, 'Main', 'checking');

  INSERT INTO public.categories (user_id, name, kind, color) VALUES
    (NEW.id, 'Groceries',     'expense', '#22c55e'),
    (NEW.id, 'Eating Out',    'expense', '#f97316'),
    (NEW.id, 'Transport',     'expense', '#3b82f6'),
    (NEW.id, 'Housing',       'expense', '#8b5cf6'),
    (NEW.id, 'Utilities',     'expense', '#06b6d4'),
    (NEW.id, 'Health',        'expense', '#ef4444'),
    (NEW.id, 'Shopping',      'expense', '#ec4899'),
    (NEW.id, 'Entertainment', 'expense', '#eab308'),
    (NEW.id, 'Subscriptions', 'expense', '#14b8a6'),
    (NEW.id, 'Other',         'expense', '#64748b'),
    (NEW.id, 'Salary',        'income',  '#16a34a'),
    (NEW.id, 'Other Income',  'income',  '#65a30d');

  RETURN NEW;
END;
$$;--> statement-breakpoint
DROP TRIGGER IF EXISTS "on_auth_user_created" ON "auth"."users";--> statement-breakpoint
CREATE TRIGGER "on_auth_user_created" AFTER INSERT ON "auth"."users" FOR EACH ROW EXECUTE FUNCTION "public"."handle_new_user"();--> statement-breakpoint
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."transactions";--> statement-breakpoint
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."budgets";