CREATE TABLE "savings_contributions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"goal_id" uuid NOT NULL,
	"amount" integer NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "savings_goals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"target_amount" integer NOT NULL,
	"target_date" date,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "savings_contributions" ADD CONSTRAINT "savings_contributions_goal_id_savings_goals_id_fk" FOREIGN KEY ("goal_id") REFERENCES "public"."savings_goals"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "savings_contributions_user_idx" ON "savings_contributions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "savings_contributions_goal_idx" ON "savings_contributions" USING btree ("goal_id");--> statement-breakpoint
CREATE INDEX "savings_goals_user_idx" ON "savings_goals" USING btree ("user_id");--> statement-breakpoint
-- ===========================================================================
-- Hand-authored (not generated by drizzle-kit): auth.users FKs, CHECK
-- constraints, RLS + policies, realtime publication.
-- See docs/conventions.md -> "Building a feature - the layer order", step 1.
--
-- Rollback (manual, reversible):
--   DROP POLICY "own savings_contributions" ON "savings_contributions";
--   DROP POLICY "own savings_goals" ON "savings_goals";
--   DROP TABLE "savings_contributions";   -- also removes it from the publication
--   DROP TABLE "savings_goals";
-- ===========================================================================
ALTER TABLE "savings_goals" ADD CONSTRAINT "savings_goals_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "savings_contributions" ADD CONSTRAINT "savings_contributions_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "savings_goals" ADD CONSTRAINT "savings_goals_target_positive" CHECK ("target_amount" > 0);--> statement-breakpoint
ALTER TABLE "savings_contributions" ADD CONSTRAINT "savings_contributions_amount_nonzero" CHECK ("amount" <> 0);--> statement-breakpoint
ALTER TABLE "savings_goals" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "savings_contributions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "own savings_goals" ON "savings_goals" FOR ALL TO authenticated USING ((SELECT auth.uid()) = "user_id") WITH CHECK ((SELECT auth.uid()) = "user_id");--> statement-breakpoint
CREATE POLICY "own savings_contributions" ON "savings_contributions" FOR ALL TO authenticated USING ((SELECT auth.uid()) = "user_id") WITH CHECK ((SELECT auth.uid()) = "user_id");--> statement-breakpoint
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."savings_goals";--> statement-breakpoint
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."savings_contributions";