CREATE TABLE "recurring_series" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"merchant_entity_id" text NOT NULL,
	"account_id" uuid NOT NULL,
	"direction" "txn_direction" NOT NULL,
	"event_role" text NOT NULL,
	"cadence" text NOT NULL,
	"expected_amount" integer NOT NULL,
	"amount_tolerance_minor" integer NOT NULL,
	"last_occurred_at" timestamp with time zone NOT NULL,
	"next_expected_at" timestamp with time zone NOT NULL,
	"observation_count" integer NOT NULL,
	"status" text DEFAULT 'CANDIDATE' NOT NULL,
	"muted_at" timestamp with time zone,
	"overridden_by_user" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "recurring_series_event_role_valid" CHECK ("recurring_series"."event_role" in ('PURCHASE','INCOME','FEE','INTEREST')),
	CONSTRAINT "recurring_series_cadence_valid" CHECK ("recurring_series"."cadence" in ('WEEKLY','BIWEEKLY','SEMIMONTHLY','MONTHLY','ANNUAL')),
	CONSTRAINT "recurring_series_status_valid" CHECK ("recurring_series"."status" in ('CANDIDATE','ACTIVE','MUTED')),
	CONSTRAINT "recurring_series_expected_amount_positive" CHECK ("recurring_series"."expected_amount" > 0),
	CONSTRAINT "recurring_series_tolerance_nonnegative" CHECK ("recurring_series"."amount_tolerance_minor" >= 0),
	CONSTRAINT "recurring_series_observation_count_min" CHECK ("recurring_series"."observation_count" >= 2)
);
--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "recurring_last_scan_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "recurring_series" ADD CONSTRAINT "recurring_series_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "recurring_series_identity_uq" ON "recurring_series" USING btree ("user_id","merchant_entity_id","account_id","direction");--> statement-breakpoint
CREATE INDEX "recurring_series_user_idx" ON "recurring_series" USING btree ("user_id");--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_recurring_stream_id_recurring_series_id_fk" FOREIGN KEY ("recurring_stream_id") REFERENCES "public"."recurring_series"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "transactions_recurring_candidate_idx" ON "transactions" USING btree ("user_id","merchant_entity_id","account_id","direction","occurred_at") WHERE "transactions"."merchant_entity_id" is not null;
-- ===========================================================================
-- Hand-authored (not generated by drizzle-kit): auth.users FK, RLS + policy.
-- V1.5 recurring detection — design doc
-- docs/specs/2026-09-16-recurring-detection-design.md.
-- recurring_series is written only by the service-role detection job
-- (src/lib/plaid/recurring-store.ts), never by the request-scoped client —
-- same posture as plaid_items/plaid_accounts. The RLS policy is still a
-- normal per-user "own rows" grant (not deny-all): a future dashboard reads
-- a user's own series through their session client, exactly like every
-- other per-user table, so it must already be scoped and ready.
-- `profiles.recurring_last_scan_at` needs no new policy — profiles already
-- has RLS from Phase 1; this is just an additive nullable column on it.
-- No realtime publication change (no UI subscribes to recurring_series yet).
-- See docs/conventions.md -> "Building a feature - the layer order", step 1.
--
-- Rollback (manual, reversible):
--   DROP POLICY "own recurring_series" ON "recurring_series";
--   ALTER TABLE "transactions"
--     DROP CONSTRAINT "transactions_recurring_stream_id_recurring_series_id_fk";
--   DROP INDEX "transactions_recurring_candidate_idx";
--   ALTER TABLE "profiles" DROP COLUMN "recurring_last_scan_at";
--   DROP TABLE "recurring_series";
-- ===========================================================================
ALTER TABLE "recurring_series" ADD CONSTRAINT "recurring_series_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "recurring_series" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "own recurring_series" ON "recurring_series" FOR ALL TO authenticated USING ((SELECT auth.uid()) = "user_id") WITH CHECK ((SELECT auth.uid()) = "user_id");