CREATE TABLE "account_deletions" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"state" text DEFAULT 'deleting' NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "account_deletions_state_valid" CHECK ("account_deletions"."state" in ('deleting','deleted'))
);
--> statement-breakpoint
-- ===========================================================================
-- Hand-authored (not generated by drizzle-kit): the auth.users FK, RLS, the guard function and the RESTRICTIVE
-- policies. Design: docs/specs/2026-09-19-account-deletion-design.md ("write guard").
--
-- Why: once account deletion starts, a user-originated write must fail even with a still-valid access token.
-- Signing the user out does not do that (a JWT stays valid until `exp`), and on Path B the auth.users row is kept,
-- so no FK refuses the write either. So the rule lives in the database: a row in account_deletions => the guard
-- policies below reject INSERT/UPDATE/DELETE for that auth.uid(). Reads are untouched (the UI shows progress).
--
-- Nothing existing is weakened: each table keeps its "own ..." permissive policy; the new policies are
-- RESTRICTIVE, so they AND with it. service_role and the server's direct connection bypass RLS and can still
-- complete the deletion.
--
-- The guard is a SECURITY DEFINER function because account_deletions is deny-all to clients: a policy that read the
-- table directly would see zero rows and never fire. It has an empty search_path, only reads the caller's own
-- state, and EXECUTE is limited to `authenticated` (RLS evaluates it as the caller).
--
-- Rollback (manual, reversible):
--   -- for each table T in the list in the DO block below:
--   --   DROP POLICY "deletion guard insert" ON public.T;  (and "deletion guard update", "deletion guard delete")
--   DROP FUNCTION "public"."account_accepts_writes"();
--   DROP TABLE "account_deletions";
-- ===========================================================================
ALTER TABLE "account_deletions" ADD CONSTRAINT "account_deletions_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "account_deletions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "deny client access account_deletions" ON "account_deletions" FOR ALL TO authenticated USING (false) WITH CHECK (false);--> statement-breakpoint
CREATE FUNCTION "public"."account_accepts_writes"() RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$
  SELECT NOT EXISTS (SELECT 1 FROM public.account_deletions d WHERE d.user_id = auth.uid())
$$;--> statement-breakpoint
REVOKE ALL ON FUNCTION "public"."account_accepts_writes"() FROM PUBLIC, anon;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION "public"."account_accepts_writes"() TO authenticated;--> statement-breakpoint
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'profiles', 'accounts', 'categories', 'transactions', 'budgets', 'savings_goals', 'savings_contributions',
    'plaid_items', 'plaid_accounts', 'plaid_merchant_rules', 'recurring_series'
  ]
  LOOP
    EXECUTE format('CREATE POLICY "deletion guard insert" ON public.%I AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK ((SELECT public.account_accepts_writes()))', t);
    EXECUTE format('CREATE POLICY "deletion guard update" ON public.%I AS RESTRICTIVE FOR UPDATE TO authenticated USING ((SELECT public.account_accepts_writes())) WITH CHECK ((SELECT public.account_accepts_writes()))', t);
    EXECUTE format('CREATE POLICY "deletion guard delete" ON public.%I AS RESTRICTIVE FOR DELETE TO authenticated USING ((SELECT public.account_accepts_writes()))', t);
  END LOOP;
END $$;
