CREATE TABLE "billing_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider" text NOT NULL,
	"provider_event_id" text NOT NULL,
	"event_type" text NOT NULL,
	"internal_type" text,
	"user_id" uuid,
	"app_user_id" text,
	"environment" text NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"status" text DEFAULT 'received' NOT NULL,
	"processed_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"error" text,
	"payload" jsonb NOT NULL,
	CONSTRAINT "billing_events_environment_valid" CHECK ("billing_events"."environment" in ('production','sandbox')),
	CONSTRAINT "billing_events_status_valid" CHECK ("billing_events"."status" in ('received','processed','ignored','quarantined','failed'))
);
--> statement-breakpoint
CREATE TABLE "entitlements" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"state" text DEFAULT 'none' NOT NULL,
	"provider" text,
	"store" text,
	"product_id" text,
	"provider_customer_id" text,
	"will_renew" boolean DEFAULT false NOT NULL,
	"trial_started_at" timestamp with time zone,
	"trial_ends_at" timestamp with time zone,
	"access_until" timestamp with time zone,
	"last_provider_event_at" timestamp with time zone,
	"last_reconciled_at" timestamp with time zone,
	"renewal_price_amount" integer,
	"renewal_price_currency" text,
	"reminder_for_trial_ends_at" timestamp with time zone,
	"reminder_claimed_at" timestamp with time zone,
	"reminder_sent_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "entitlements_state_valid" CHECK ("entitlements"."state" in ('none','trialing','active','grace','expired','revoked')),
	CONSTRAINT "entitlements_store_valid" CHECK ("entitlements"."store" is null or "entitlements"."store" in ('apple','google')),
	CONSTRAINT "entitlements_currency_valid" CHECK ("entitlements"."renewal_price_currency" is null or "entitlements"."renewal_price_currency" ~ '^[A-Z]{3}$'),
	CONSTRAINT "entitlements_price_nonnegative" CHECK ("entitlements"."renewal_price_amount" is null or "entitlements"."renewal_price_amount" >= 0),
	CONSTRAINT "entitlements_access_until_when_entitled" CHECK ("entitlements"."state" not in ('trialing','active','grace') or "entitlements"."access_until" is not null),
	CONSTRAINT "entitlements_trial_ends_when_trialing" CHECK ("entitlements"."state" <> 'trialing' or "entitlements"."trial_ends_at" is not null)
);
--> statement-breakpoint
CREATE UNIQUE INDEX "billing_events_provider_event_uq" ON "billing_events" USING btree ("provider","provider_event_id");--> statement-breakpoint
CREATE INDEX "billing_events_user_idx" ON "billing_events" USING btree ("user_id","occurred_at") WHERE "billing_events"."user_id" is not null;--> statement-breakpoint
CREATE INDEX "billing_events_pending_idx" ON "billing_events" USING btree ("received_at") WHERE "billing_events"."status" in ('received','failed');--> statement-breakpoint
CREATE INDEX "entitlements_trial_reminder_idx" ON "entitlements" USING btree ("trial_ends_at") WHERE "entitlements"."state" = 'trialing';--> statement-breakpoint
CREATE INDEX "entitlements_reconcile_idx" ON "entitlements" USING btree ("last_reconciled_at") WHERE "entitlements"."state" in ('trialing','active','grace');
--> statement-breakpoint
-- ===========================================================================
-- Hand-authored (not generated by drizzle-kit): the auth.users FKs, RLS + policies, and the billing_events
-- immutability trigger. V1 subscription entitlement (the authoritative "does this user have Premium" state) and the
-- provider webhook event log. Design: docs/specs/2026-09-21-v1-monetization-design.md.
--
-- Both user FKs are ON DELETE CASCADE, unlike the financial ledger (0021, RESTRICT): an entitlement that never
-- became a paid charge is NOT monetization history, so a trial-only user must stay eligible for Path A hard
-- deletion. Path B (paid history) keeps the auth.users row, so it deletes the entitlement explicitly instead
-- (src/lib/account/deletion-store.ts) and retains billing_events as the audit trail for the retained ledger.
--
-- RLS: entitlements is readable by its owner only and has NO authenticated INSERT/UPDATE/DELETE policy - every write
-- comes from the server, so the deletion write guard (0019) has nothing to add here. billing_events is deny-all.
--
-- Rollback (manual, reversible):
--   DROP TRIGGER "billing_events_guard_mutation" ON "billing_events";
--   DROP FUNCTION "public"."billing_events_guard_mutation"();
--   DROP POLICY "own read entitlements" ON "entitlements";
--   DROP POLICY "deny client access billing_events" ON "billing_events";
--   ALTER TABLE "entitlements" DROP CONSTRAINT "entitlements_user_id_auth_users_fk";
--   ALTER TABLE "billing_events" DROP CONSTRAINT "billing_events_user_id_auth_users_fk";
--   DROP TABLE "billing_events"; DROP TABLE "entitlements";
-- ===========================================================================
ALTER TABLE "entitlements" ADD CONSTRAINT "entitlements_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "billing_events" ADD CONSTRAINT "billing_events_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint

ALTER TABLE "entitlements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "billing_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "own read entitlements" ON "entitlements" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = "user_id");--> statement-breakpoint
CREATE POLICY "deny client access billing_events" ON "billing_events" FOR ALL TO authenticated USING (false) WITH CHECK (false);--> statement-breakpoint

-- billing_events: the event's identity and its (redacted) payload are frozen; only the processing bookkeeping moves,
-- and a terminal outcome (processed / ignored / quarantined) is final. A duplicate delivery therefore cannot
-- re-open a handled event, and nothing can rewrite what a provider said.
CREATE FUNCTION "public"."billing_events_guard_mutation"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."provider" IS DISTINCT FROM OLD."provider"
     OR NEW."provider_event_id" IS DISTINCT FROM OLD."provider_event_id"
     OR NEW."event_type" IS DISTINCT FROM OLD."event_type"
     OR NEW."user_id" IS DISTINCT FROM OLD."user_id"
     OR NEW."app_user_id" IS DISTINCT FROM OLD."app_user_id"
     OR NEW."environment" IS DISTINCT FROM OLD."environment"
     OR NEW."occurred_at" IS DISTINCT FROM OLD."occurred_at"
     OR NEW."received_at" IS DISTINCT FROM OLD."received_at"
     OR NEW."payload" IS DISTINCT FROM OLD."payload"
  THEN
    RAISE EXCEPTION 'billing_events identity and payload are immutable (id=%)', OLD.id;
  END IF;
  IF OLD."status" IN ('processed','ignored','quarantined') AND NEW."status" IS DISTINCT FROM OLD."status" THEN
    RAISE EXCEPTION 'billing_events status % is terminal (id=%)', OLD."status", OLD.id;
  END IF;
  RETURN NEW;
END;
$$;--> statement-breakpoint

CREATE TRIGGER "billing_events_guard_mutation"
  BEFORE UPDATE ON "billing_events"
  FOR EACH ROW EXECUTE FUNCTION "public"."billing_events_guard_mutation"();
