CREATE TABLE "plaid_sign_answers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"plaid_account_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"answer" text NOT NULL,
	"sample_transaction_id" uuid,
	"from_convention" "plaid_sign_convention" NOT NULL,
	"to_convention" "plaid_sign_convention" NOT NULL,
	"changed_rows" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "plaid_sign_answers_kind_valid" CHECK ("plaid_sign_answers"."kind" in ('answer','change')),
	CONSTRAINT "plaid_sign_answers_answer_valid" CHECK ("plaid_sign_answers"."answer" in ('out','in')),
	CONSTRAINT "plaid_sign_answers_resolves" CHECK ("plaid_sign_answers"."to_convention" <> 'unknown' and "plaid_sign_answers"."from_convention" <> "plaid_sign_answers"."to_convention")
);
--> statement-breakpoint
ALTER TABLE "plaid_sign_answers" ADD CONSTRAINT "plaid_sign_answers_plaid_account_id_plaid_accounts_id_fk" FOREIGN KEY ("plaid_account_id") REFERENCES "public"."plaid_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plaid_sign_answers" ADD CONSTRAINT "plaid_sign_answers_sample_transaction_id_transactions_id_fk" FOREIGN KEY ("sample_transaction_id") REFERENCES "public"."transactions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "plaid_sign_answers_account_idx" ON "plaid_sign_answers" USING btree ("plaid_account_id","created_at");--> statement-breakpoint
CREATE INDEX "plaid_sign_answers_user_idx" ON "plaid_sign_answers" USING btree ("user_id");
--> statement-breakpoint
-- ===========================================================================
-- Hand-authored (not generated by drizzle-kit): the auth.users FK and RLS. The user's answers to "Was this money going
-- out or coming in?" for a Plaid account whose transaction format never settled, and every later "Change answer"
-- (design: docs/specs/2026-10-01-card-payments-design.md §5). Rows are written only by the server
-- (src/server/plaid/sign-answer.ts, as the DB owner) and never updated; the owner can read their own.
--
-- ON DELETE CASCADE from auth.users (Path A) and from plaid_accounts (Path B removes bank connections first, and a
-- disconnect removes the account): operational data, not monetization history.
--
-- Rollback (manual, reversible): remove the table plaid_sign_answers (nothing else depends on it).
-- ===========================================================================
ALTER TABLE "plaid_sign_answers" ADD CONSTRAINT "plaid_sign_answers_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "plaid_sign_answers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "own read plaid_sign_answers" ON "plaid_sign_answers" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = "user_id");