CREATE TABLE "account_bank_identities" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"account_id" uuid NOT NULL,
	"institution_id" text NOT NULL,
	"mask" text NOT NULL,
	"type" text NOT NULL,
	"subtype" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "account_bank_identities" ADD CONSTRAINT "account_bank_identities_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "account_bank_identities_uq" ON "account_bank_identities" USING btree ("account_id","institution_id","mask","type","subtype");--> statement-breakpoint
CREATE INDEX "account_bank_identities_user_institution_idx" ON "account_bank_identities" USING btree ("user_id","institution_id");
--> statement-breakpoint
-- ===========================================================================
-- Hand-authored (not generated by drizzle-kit): the auth.users FK, RLS, the recording trigger and the backfill.
--
-- Why (owner decision 2026-10-02): reconnect adoption (src/lib/plaid/reconnect-adoption.ts) re-attaches a reconnected
-- bank's re-sent history only when the new Plaid account is mapped onto the SAME Budgts account the kept history lives
-- in. Disconnecting deletes plaid_items, which cascades plaid_accounts, so nothing recorded which bank account fed
-- which Budgts account. This table keeps that identity (institution, last 4, type, subtype) per Budgts account, so the
-- mapping step can suggest the right account (src/lib/plaid/reconnect-match.ts).
--
-- Written ONLY by the trigger below, on every path that links a Plaid account to a Budgts account (insert or update of
-- plaid_accounts.account_id), so no caller can forget it. Never by a client: the owner may read their own rows.
-- An identity is recorded only for an account owned by the link's own user, with an institution and a last 4.
-- type/subtype are stored trimmed and lower-cased, '' when absent, so the unique key compares them.
--
-- ON DELETE CASCADE from auth.users (Path A) and from accounts (Path B deletes accounts explicitly): operational
-- data that goes with the account, never monetization history.
--
-- Rollback (manual, reversible): remove the trigger plaid_accounts_record_bank_identity, the function
-- public.record_account_bank_identity() and the table account_bank_identities. Nothing else depends on them.
-- ===========================================================================
ALTER TABLE "account_bank_identities" ADD CONSTRAINT "account_bank_identities_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "account_bank_identities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "own read account_bank_identities" ON "account_bank_identities" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = "user_id");--> statement-breakpoint
CREATE FUNCTION public.record_account_bank_identity() RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.account_bank_identities (user_id, account_id, institution_id, mask, type, subtype)
  SELECT NEW.user_id, NEW.account_id, i.institution_id, btrim(NEW.mask),
         lower(btrim(coalesce(NEW.type, ''))), lower(btrim(coalesce(NEW.subtype, '')))
  FROM public.plaid_items i
  JOIN public.accounts a ON a.id = NEW.account_id AND a.user_id = NEW.user_id
  WHERE i.id = NEW.plaid_item_id
    AND i.user_id = NEW.user_id
    AND i.institution_id IS NOT NULL
    AND nullif(btrim(NEW.mask), '') IS NOT NULL
  ON CONFLICT DO NOTHING;
  RETURN NULL;
END;
$$;--> statement-breakpoint
REVOKE ALL ON FUNCTION public.record_account_bank_identity() FROM PUBLIC;--> statement-breakpoint
CREATE TRIGGER plaid_accounts_record_bank_identity
AFTER INSERT OR UPDATE OF account_id, mask, type, subtype ON public.plaid_accounts
FOR EACH ROW WHEN (NEW.account_id IS NOT NULL)
EXECUTE FUNCTION public.record_account_bank_identity();--> statement-breakpoint
-- Backfill: every CURRENT link (the same rule as the trigger), so banks connected today are recognised after a later
-- disconnect. Idempotent (ON CONFLICT DO NOTHING).
INSERT INTO public.account_bank_identities (user_id, account_id, institution_id, mask, type, subtype)
SELECT pa.user_id, pa.account_id, i.institution_id, btrim(pa.mask),
       lower(btrim(coalesce(pa.type, ''))), lower(btrim(coalesce(pa.subtype, '')))
FROM public.plaid_accounts pa
JOIN public.plaid_items i ON i.id = pa.plaid_item_id AND i.user_id = pa.user_id
JOIN public.accounts a ON a.id = pa.account_id AND a.user_id = pa.user_id
WHERE pa.account_id IS NOT NULL
  AND i.institution_id IS NOT NULL
  AND nullif(btrim(pa.mask), '') IS NOT NULL
ON CONFLICT DO NOTHING;