CREATE TABLE "detached_sign_answers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"account_id" uuid NOT NULL,
	"origin_account_ref" text NOT NULL,
	"kind" text NOT NULL,
	"answer" text NOT NULL,
	"sample_transaction_id" uuid,
	"from_convention" "plaid_sign_convention" NOT NULL,
	"to_convention" "plaid_sign_convention" NOT NULL,
	"changed_rows" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "detached_sign_answers_kind_valid" CHECK ("detached_sign_answers"."kind" in ('answer','change')),
	CONSTRAINT "detached_sign_answers_answer_valid" CHECK ("detached_sign_answers"."answer" in ('out','in')),
	CONSTRAINT "detached_sign_answers_resolves" CHECK ("detached_sign_answers"."to_convention" <> 'unknown' and "detached_sign_answers"."from_convention" <> "detached_sign_answers"."to_convention")
);
--> statement-breakpoint
ALTER TABLE "detached_sign_answers" ADD CONSTRAINT "detached_sign_answers_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "detached_sign_answers" ADD CONSTRAINT "detached_sign_answers_sample_transaction_id_transactions_id_fk" FOREIGN KEY ("sample_transaction_id") REFERENCES "public"."transactions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "detached_sign_answers_group_idx" ON "detached_sign_answers" USING btree ("user_id","account_id","origin_account_ref","created_at");
--> statement-breakpoint
-- ===========================================================================
-- Hand-authored (not generated by drizzle-kit): the auth.users FK and RLS.
--
-- Why (owner-approved bug fix 2026-10-05; design: docs/specs/2026-10-01-card-payments-design.md §5c): a row held while
-- its Plaid account's sign convention was unknown is kept, detached, when the bank is disconnected (plaid_accounts is
-- deleted; transactions.plaid_account_id is ON DELETE SET NULL). The per-account question can't reach it any more, so
-- Connected banks asks it under the Budgts account instead, per original bank feed (Plaid's account_id in the row's raw
-- payload). These rows record each answer and "Change answer" with every changed row's old values. plaid_sign_answers
-- can't hold them: its plaid_account_id is NOT NULL and cascades from the deleted plaid_accounts row.
--
-- Written only by the server (src/server/plaid/detached-sign-answer.ts, as the DB owner), never updated; the owner may
-- read their own. ON DELETE CASCADE from auth.users (Path A) and from accounts (Path B deletes accounts explicitly):
-- operational data that goes with the account, never monetization history.
--
-- Rollback (manual, reversible): remove the table detached_sign_answers (nothing else depends on it).
-- ===========================================================================
ALTER TABLE "detached_sign_answers" ADD CONSTRAINT "detached_sign_answers_user_id_auth_users_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "detached_sign_answers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "own read detached_sign_answers" ON "detached_sign_answers" FOR SELECT TO authenticated USING ((SELECT auth.uid()) = "user_id");